version: '3'
services:
    myserver:
        build: ./logs-shipper
        deploy:
            replicas: ${REPLICAS}

    haproxy:
        build: ./haproxy
        ports:
            - "8080:8080"
        environment:
            - REPLICAS=${REPLICAS}
        depends_on:
            - myserver