version: '3'
services:
    server:
        build: ./logs-shipper
        deploy:
            replicas: ${REPLICAS}

    haproxy:
        build: ./haproxy
        ports:
            - "${PORT}:${PORT}"
        environment:
            - REPLICAS=${REPLICAS}
            - PORT=${PORT}