version: '3'
services:
    myserver1:
        build: ./logs-shipper

    myserver2:
        build: ./logs-shipper

    haproxy:
        build: ./haproxy
        ports:
            - "8080:8080"
        depends_on:
            - myserver1
            - myserver2
