version: '3'
services:
    server:
        build: ./logs-shipper
        volumes:
            - ./infrastructure/src/main/resources/elastic.config:/usr/app/elastic.config
            - ./infrastructure/src/main/resources/server.config:/usr/app/server.config
        deploy:
            replicas: ${REPLICAS}


    haproxy:
        build: ./haproxy
        ports:
            - "${PORT}:${PORT}"
        environment:
            - REPLICAS=${REPLICAS}
            - PORT=${PORT}

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
        container_name: elasticsearch
        ports:
            - "9200:9200"   # for REST
            - "9300:9300"        # for node communication
        environment:
            ES_JAVA_OPTS: '-Xms256m -Xmx256m' # set heap size to 256mb

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # debug on local machine
#            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # debug on local machine
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    consumer:
        build: ./indexer
        volumes:
            - ./infrastructure/src/main/resources/elastic.config:/usr/app/elastic.config
            - ./infrastructure/src/main/resources/server.config:/usr/app/server.config
        ports:
            - "9000:8080"