version: '3'
services:
    server:
        build: ./logs-shipper
        deploy:
            replicas: ${REPLICAS}

    haproxy:
        build: ./haproxy
        ports:
            - "${PORT}:${PORT}"
        environment:
            - REPLICAS=${REPLICAS}
            - PORT=${PORT}

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
        container_name: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            ES_JAVA_OPTS: '-Xms256m -Xmx256m'
            network.bind_host: 0.0.0.0
            network.host: 0.0.0.0
            discovery.type: single-node